source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"
target:testApp do
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 4.3.3'
pod 'AMap2DMap-NO-IDFA'
pod 'AMapSearch-NO-IDFA'
pod 'YYModel', '~> 1.0.4'
end
